# Generated by Django 3.2.16 on 2022-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(upload_to='posts/%Y/%m/%d/'),
        ),
    ]
